### PR TITLE
Fix picture links and images not displaying

### LINKED ISSUE #132: images not displaying, messing up caption format

### PR DESCRIPTION
**Pull request by maggarwal99**
Closes #132 and #118

### CODE REVIEW

File: static/js/play.js [hunk 1]
```diff
@@ -95,10 +97,18 @@ async function loadPage(page) {
 
     let frameBody = document.getElementById("wikipedia-frame")
     frameBody.innerHTML = body["parse"]["text"]["*"]
+
     frameBody.querySelectorAll("a").forEach(function(a) {
-        a.innerHTML = '<div style="display:inline-block">' + a.text.split('').map(function(character) {
-            return '<div style="display:inline-block">' + character.replace(/\s/g, '&nbsp;') + '</div>'
-        }).join('') + '</div>'
+        let iter = document.createNodeIterator(a, NodeFilter.SHOW_TEXT), textNode;
```
Comment (dqian3) [inline static/js/play.js:102]: split this declaration pls. it looks kind of confusing

**Review by dqian3 — APPROVED** [review]
